import styled from "@emotion/styled";
import Head from "next/head";
import { useRouter } from "next/router";


interface ILayout {
  children: React.ReactNode;
  title?: string;
}

export default function Layout({children,title}: ILayout) {
  const router = useRouter();
  
  const onClickHeader = () => {
    router.push("/");
  }

  return (
    <>
      <Head>
        <title>{title ? `NARAS | ${title}` : 'NARAS'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta property="og:image" content="/thumbnail.png" />
        <meta property="og:title" content="NARAS" />
        <meta
          property="og:description"
          content="전 세계 국가들의 정보를 확인해보세요"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SHeader onClick={onClickHeader}>🌏 NARAS</SHeader>
      <h1 className="a11yHidden">NARAS</h1>
      <SMain>{children}</SMain>
    </>
  );
}

const SHeader = styled.header`
  position: fixed;
  top: 0px;
  left: 0px;
  right: 0px;
  height: 50px;
  background-color: white;
  display: flex;
  align-items: center;
  justify-content: center;
  font-weight: bold;
  cursor: pointer;
  z-index: 10;
`;

const SMain = styled.main`
  max-width: 720px;
  margin: 0 auto;
  padding: 80px 10px;

  display: flex;
  flex-direction: column;
  gap: 20px;
`;